### ISSUE TITLE
  http Error: error:0906D06C:PEM routines:PEM_read_bio:no start line

### ISSUE THREAD

**Issue by vijay-nts** [Nordstrom/artillery-plugin-http-ssl#3]
Hi
I tried to use this plugin for artillery load test and when it runs I am getting the following error. Please help me to solve this issue.

**http Error: error:0906D06C:PEM routines:PEM_read_bio:no start line** 

My Yml file : 
config:
  #target: '****.com'
  target: 'UAT'
  http:
  tls:
    ca: "./generic-keystore-interCA"
    #cert: keystore.tla-w01car0119
    key: "./keystore.tla-w01car0119"
    passphrase: "..."
  plugins:
    http-ssl: {}

Log File : 

runner Plugin http-ssl loaded from artillery-plugin-http-ssl +3ms
  runner run() with: {"config":{"target":"UAT","http":null,"tls":{"ca":{"type":"Buffer","data":[...]},"key":{"type":"Buffer","data":[...]},"passphrase":"...","rejectUnauthorized":false},"plugins":{"http-ssl":{}},"phases":[{"duration":1,"arrivalRate":1,"name":"Load Test "}],"statsInterval":10,"payload":[]},"scenarios":[{"flow":[{"post":{"url":"https://***/***/restws/async/v1/mailorder/status","sslAuth":false,"Json":{"orderPlacedDttm":"12:16 PM Jul 06, 2018","orderActionDttm":"12:16 PM Jul 06, 2018","gqmOrderId":2149974,"trackingNbr":"UPSTESTNUMBEROVERNIGHT","shipToMethodCd":"ON","carrierId":"1","reasonCd":null,"reasonDesc":null,"statusCd":"PAID","orderStatusInd":1,"failedCnt":0,"vendorOrderId":"667101221197","transactionId":"123","context":null,"origin":"Mail","timestamp":"2018-05-01T23:15:59","orgType":"1","storeNo":"null","channelCd":"","channelDetailCd":"","functionalityCd":"","ipaddress":""}}}]}],"payload":[]} +1ms
Started phase 0 (Load Test ), duration: 1s @ 16:59:20(-0500) 2018-07-24
⠋   phases creating a uniform process for arrivalRate +5ms
  arrivals tickInterval = 1000, duration = 1000 +0ms
  arrivals this._tickInterval set to 1000000 +1ms
  arrivals maxArrivals = 1 +0ms
⠹   runner picking scenario 0 (undefined) weight = 1 +1s
  perf runScenarioDelta: 2.15 +1ms
  arrivals maxArrivals reached, stopping +1s
  runner All phases launched +0ms
  http Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
  http     at Object.createSecureContext (_tls_common.js:104:17)
  http     at Object.exports.connect (_tls_wrap.js:1049:48)
  http     at Agent.createConnection (https.js:111:22)
  http     at Agent.createSocket (_http_agent.js:227:26)
  http     at Agent.addRequest (_http_agent.js:185:10)
  http     at new ClientRequest (_http_client.js:258:16)
  http     at Object.request (http.js:38:10)
  http     at Object.request (https.js:239:15)
  http     at Request.start (/usr/local/lib/node_modules/artillery/node_modules/request/request.js:747:32)
  http     at Request.end (/usr/local/lib/node_modules/artillery/node_modules/request/request.js:1506:10) +13ms
  runner Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
  runner     at Object.createSecureContext (_tls_common.js:104:17)
  runner     at Object.exports.connect (_tls_wrap.js:1049:48)
  runner     at Agent.createConnection (https.js:111:22)
  runner     at Agent.createSocket (_http_agent.js:227:26)
  runner     at Agent.addRequest (_http_agent.js:185:10)
  runner     at new ClientRequest (_http_client.js:258:16)
  runner     at Object.request (http.js:38:10)
  runner     at Object.request (https.js:239:15)
  runner     at Request.start (/usr/local/lib/node_modules/artillery/node_modules/request/request.js:747:32)
  runner     at Request.end (/usr/local/lib/node_modules/artillery/node_modules/request/request.js:1506:10) +1ms
Report @ 16:59:21(-0500) 2018-07-24
  Scenarios launched:  1
  Scenarios completed: 0
  Requests completed:  0
  RPS sent: NaN
  Request latency:
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
  Errors:
    error:0906D06C:PEM routines:PEM_read_bio:no start line: 1

[edit by @erikerikson replaced ca, key, and passphrase values with elipsis ("...")]

**Comment by erikerikson** [comment]
Pretty sure you just shared your key with us.  You will probably want to rotate it.

**Comment by erikerikson** [comment]
That written, I'd trust the message to be meaningful.  If you note the code, it is extremely simple, merely reading in the given files so that the config is passed to requestjs.

You can debug your scenario using the code sample listed at the link in this repo's README: https://github.com/request/request#tlsssl-protocol

**Comment by vijay-nts** [comment]
Thank You

**Comment by erikerikson** [comment]
You bet.  Please attempt to use the code linked to by [my comment](https://github.com/Nordstrom/artillery-plugin-http-ssl/issues/3#issuecomment-407570287) and troubleshoot.  If you have that code working but the plugin remains broken, we'll be happy to help you sort out the cause.

Otherwise, please close the issue as you resolve your issue.

**Comment by vijay-nts** [comment]
Working fine..Thanks for sharing code to troubleshoot.
